<?php
/**
 * Dotdigital - https://dotdigital.com
 * Copyright © Dotdigital Group PLC 2024-present. All rights reserved.
 * This code may be used in conjunction with the module dotdigital/dotdigital-magento2-extension
 * See https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/LICENSE.md
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Dotdigitalgroup\Chat\ViewModel\ChatProfile;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HyvaCsp;

/**
 * @var Escaper $escaper
 * @var Template $block
 * @var ChatProfile $viewModel
 * @var HyvaCsp $hyvaCsp
 */

$viewModel = $block->getData('view_model');
$chatData = $viewModel->getChatConfig();
?>

<?php if ($chatData['isEnabled']): ?>
    <script>
        const chatData = <?= /* @noEscape */json_encode($chatData); ?>;
        const {apiSpaceId, isEnabled, apiHost, profileEndpoint, cookieName} = chatData;

        window.addEventListener('message', (event) => {
            const {type, show} = event.data;

            if (type !== 'SetWidgetState') return;

            if (show === 'hidden') {
                sessionStorage.removeItem(cookieName);
            } else if (!sessionStorage.getItem(cookieName)) {
                window.COMAPI_WIDGET_API.profile.getProfile()
                    .then(profile => {
                        fetch(profileEndpoint, {
                            method: 'POST',
                            body: "profileId=" + profile.id,
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded',
                                'X-Requested-With': 'XMLHttpRequest'
                            },
                        })
                            .then(() => {
                                sessionStorage.setItem(cookieName, profile.id);
                                document.cookie = `${cookieName}=${profile.id}`;
                            })
                            .catch(console.error);
                    });
            }
        });
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
<?php endif; ?>
